#!/bin/bash
git config --global user.name "Tung Nguyen"
git config --global user.email tung.nk41@gmail.com
git config --global core.editor "vim"

#Test ssh
#ssh -T git@github.com

#Create Repo
#git init
#git remote add $RepoName $LinkGitRepoServer
#git add $file
#git push $RepoName $Branch
